name: Publish package 2

on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Directory?'
        required: true

jobs:
  publish-second:
    uses: ./.github/workflows/publish.yaml@main
    with:
      WORKING_DIRECTORY: ${{ inputs.directory }}
      PACKAGE_NAME: 'ts-custom-pkg'
