name: Publish package

on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Directory?'
        required: true

jobs:
  publish:
    uses: .github/workflows/publish.yaml
    with:
      WORKING_DIRECTORY: ${{ inputs.directory }}
      PACKAGE_NAME: 'ts-custom-pkg'
